//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangeLog
    {
        public Nullable<int> FK_TableId { get; set; }
        public Nullable<int> FK_UserId { get; set; }
        public Nullable<int> FK_CallingUserId { get; set; }
        public byte Operation { get; set; }
        public Nullable<int> LololNo { get; set; }
        public Nullable<int> OKAYMORE { get; set; }
    
        public virtual TableListing TableListing { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
