//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class NavigationHistory
    {
        public int Id { get; set; }
        public Nullable<int> FK_UserId { get; set; }
        public Nullable<int> FK_PageId { get; set; }
        public System.DateTime TimeStamp { get; set; }
    
        public virtual Page Page { get; set; }
        public virtual User User { get; set; }
    }
}
