//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class Password
    {
        public Nullable<int> FK_UserId { get; set; }
        public string Salt { get; set; }
        public string HashedPassword { get; set; }
        public Nullable<byte> Attempts { get; set; }
        public Nullable<bool> Expires { get; set; }
        public System.DateTime Expiration { get; set; }
        public Nullable<bool> IsLocked { get; set; }
    
        public virtual User User { get; set; }
    }
}
