//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Post()
        {
            this.PostComments = new HashSet<PostComment>();
            this.PostEditHistories = new HashSet<PostEditHistory>();
        }
    
        public int Id { get; set; }
        public Nullable<int> FK_UserId { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public Nullable<bool> IsPubliclyVisible { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostComment> PostComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostEditHistory> PostEditHistories { get; set; }
        public virtual User User { get; set; }
    }
}
